### ISSUE TITLE
[BUG?] Kubernetes status shows up as "down" but services are up

### ISSUE THREAD

**Issue by shamoon** [gethomepage/homepage#3755]
### Discussed in https://github.com/gethomepage/homepage/discussions/3751

<div type='discussions-op-text'>

<sup>Originally posted by **geberl** July 17, 2024</sup>
### Description

Probably introduced by https://github.com/gethomepage/homepage/pull/3735

### homepage version

v0.9.4

### Installation method

Docker

### Troubleshooting

Was working perfectly in v0.9.3</div>

**Comment by shamoon** [comment]
Closed by #3753

**Comment by Skaronator** [comment]
Thanks for the quick fix! However, the removal of the 0.9.4 release on GitHub led to some extra debugging on my part.

I initially only verified that Renovate had updated the homepage, which it clearly had, but I neglected to double-check the version number. When I looked at the GitHub releases page, I saw one from an hour ago and the previous one from a week ago. This led me to believe that the recent release was problematic.

Upon examining the PR and issue, though, it seemed unlikely to be broken since it included precisely these fixes. It took me a few minutes to realize that Renovate had actually updated to the now-absent 0.9.4 release, and that 0.9.5 addressed my issue.

It would be cool to just leave the GitHub releases, even if they contain bugs :)
